apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    project: ai-self-healing-k8s
    component: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-engine
  labels:
    project: ai-self-healing-k8s
    component: ai-brain
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-app
  labels:
    project: ai-self-healing-k8s
    component: workload
